query CurrentUser {
    currentUser {
        username
        _id
        admin
        avatar
    }
}

query GetUsers {
    users {
        _id
        username
        admin
        avatar
    }
}

query IsUserOccupied ($username: String!){
    isUserOccupied(username: $username)
}

mutation Login($loginInput: loginInput!) {
    login(loginInput: $loginInput) {
        accessToken
    }
}

mutation SignIn($userInput: userInput!) {
    createUser(userInput: $userInput) {
        username
        _id
    }
}


mutation UpdateUser($id: String!, $userInput: userInput!) {
    updateUser(_id: $id, userInput: $userInput) {
        username
        _id
    }
}


mutation UploadFile($file: Upload!, $userId: String!) {
    uploadFile(file: $file, userId: $userId)
}
