query CurrentUser {
    currentUser {
        username
        _id
        admin
    }
}

query GetUsers {
    users {
        _id
        username
        admin
    }
}

mutation Login($loginInput: loginInput!) {
    login(loginInput: $loginInput) {
        accessToken
    }
}

mutation SignIn($userInput: userInput!) {
    createUser(userInput: $userInput) {
        username
        _id
    }
}


mutation UpdateUser($id: String!, $userInput: userInput!) {
    updateUser(_id: $id, userInput: $userInput) {
        username
        _id
    }
}
