query GetCats {
    cats {
        _id
        breed
        filenames
        characteristics {
            color
            coat
            lifespan
            size
        }
    }
}

mutation DeleteCat($id: String!) {
    deleteCat(_id: $id) {
        breed
    }
}

mutation UpdateCat(
    $id: String!,
    $catInput: CatInput!
    $files: [Upload!]!
    $filenames: [String!]!
) {
    updateCat(
        _id: $id,
        catInput: $catInput,
        filenames: $filenames,
        files: $files
    ) {
        breed
    }
}

mutation CreateCat(
    $catInput: CatInput!
    $files: [Upload!]!
) {
    createCat(
        catInput: $catInput
        files: $files
    ) {
        breed
    }
}


mutation UploadCatPhotos($id: String!, $files: [Upload!]!) {
    uploadCatPhotos(_id: $id, files: $files)
}

