    query GetCats {
        cats {
            _id
            breed
            characteristics {
                color
                coat
                lifespan
                size
            }
        }
    }

    mutation DeleteCat($id: String!) {
        deleteCat(_id: $id) {
            breed
        }
    }

