    query GetCats {
        cats {
            _id
            breed
            characteristics {
                color
                coat
                lifespan
                size
            }
        }
    }

    query GetTodos {
        todos {
            _id
            description
            completed
            due
            locked
            user {
                _id
                username
            }
        }
    }

    query CurrentUser {
        currentUser {
            username
            _id
        }
    }

    query GetUsers {
        users {
            _id
            username
        }
    }

    mutation Login($userInput: userInput!) {
        login(userInput: $userInput) {
            accessToken
        }
    }

    mutation SignIn($userInput: userInput!) {
        createUser(userInput: $userInput) {
            username
            _id
        }
    }

    mutation DeleteCat($id: String!) {
        deleteCat(_id: $id) {
            breed
        }
    }

    mutation UpdateCat($id: String!, $catInput: CatInput!) {
        updateCat(_id: $id, catInput: $catInput) {
            breed
        }
    }

    mutation CreateCat($catInput: CatInput!) {
        createCat(catInput: $catInput) {
            breed
        }
    }

    mutation DeleteTodo($id: String!) {
        deleteTodo(_id: $id) {
            description
        }
    }

    mutation UpdateTodo($id: String!, $todoInput: TodoInput!) {
        updateTodo(_id: $id, todoInput: $todoInput) {
            description
        }
    }

    mutation CreateTodo($todoInput: TodoInput!) {
        createTodo(todoInput: $todoInput) {
            description
        }
    }

    subscription Todo {
        todo {
            description
        }
    }

