query GetNotes (
    $offset: Float,
    $limit: Float,
){
    notes (limit: $limit, offset: $offset) {
        count
        notes {
            id
            title
            markdownContent
            author {
                username
                _id
            }
        }
    }
}

mutation CreateNote($noteInput: NoteInput!) {
    createNote(noteInput: $noteInput) {
        title
    }
}

mutation UpdateNote($id: Float!, $noteInput: NoteInput!) {
    updateNote(id: $id, noteInput: $noteInput) {
        title
    }
}

mutation DeleteNote($id: Float!) {
    deleteNote(id: $id) {
        title
    }
}
